namespace Divert.Windows;

public enum DivertEvent
{
    NetworkPacket = WINDIVERT_EVENT.WINDIVERT_EVENT_NETWORK_PACKET,
    FlowEstablished = WINDIVERT_EVENT.WINDIVERT_EVENT_FLOW_ESTABLISHED,
    FlowDeleted = WINDIVERT_EVENT.WINDIVERT_EVENT_FLOW_DELETED,
    SocketBind = WINDIVERT_EVENT.WINDIVERT_EVENT_SOCKET_BIND,
    SocketConnect = WINDIVERT_EVENT.WINDIVERT_EVENT_SOCKET_CONNECT,
    SocketListen = WINDIVERT_EVENT.WINDIVERT_EVENT_SOCKET_LISTEN,
    SocketAccept = WINDIVERT_EVENT.WINDIVERT_EVENT_SOCKET_ACCEPT,
    SocketClose = WINDIVERT_EVENT.WINDIVERT_EVENT_SOCKET_CLOSE,
    ReflectOpen = WINDIVERT_EVENT.WINDIVERT_EVENT_REFLECT_OPEN,
    ReflectClose = WINDIVERT_EVENT.WINDIVERT_EVENT_REFLECT_CLOSE,
}
