namespace Divert.Windows;

public enum DivertLayer
{
    Network = WINDIVERT_LAYER.WINDIVERT_LAYER_NETWORK,
    Forward = WINDIVERT_LAYER.WINDIVERT_LAYER_NETWORK_FORWARD,
    Flow = WINDIVERT_LAYER.WINDIVERT_LAYER_FLOW,
    Socket = WINDIVERT_LAYER.WINDIVERT_LAYER_SOCKET,
    Reflect = WINDIVERT_LAYER.WINDIVERT_LAYER_REFLECT,
}
